### ISSUE TITLE
Support has_and_belongs_to_many with alias on relation name

### ISSUE THREAD

**Issue by bmedici** [deepcerulean/passive_record#11]
Hello, 

When we have a model containing some children, but also related to the model upstream, we cannot delcare a has_and_belongs_to_many relationship.
Example: 
```
class Application < Model
  belongs_to :group
  has_many :services
  has_and_belongs_to_many :dependencies, model_name: "Service"
end

class Service < Model
  belongs_to :application
  has_and_belongs_to_many :clients, model_name: 'Application'
end
```
An Application has many services offered by itself, and depends on many other Services (relation: dependencies). In this case, as we have:
```
associations.rb:173:in `has_and_belongs_to_many': wrong number of arg
uments (given 2, expected 1)
```
Maybe I'm missing something, but this would be really great to be able to name each relation the way we want, in order to have complex relations.

Thanks !

**Comment by jweissman** [comment]
Thanks for sharing this use case. This is pretty interesting, and sorry for taking so long to respond! Just glancing over the source quickly -- there is so much granular metaprogramming around symbol names in the current implementation that this might actually be pretty challenging without refactoring several other things. I was thinking about rebuilding this for Ruby 3 so definitely appreciate this as a potential design requirement
