### ISSUE TITLE
attribute example

### ISSUE THREAD

**Issue by Skeyelab** [deepcerulean/passive_record#8]
I cannot figure out how to declare attributes.  Can you provide an example?

**Comment by Skeyelab** [comment]
so in the example in spec_helper, I could do:

```
d = Dog.create
d.breed = "Pitbull"
```

**Comment by jweissman** [comment]
@Skeyelab yes, definitely. You could also `d.update(breed: "Pitbull")` if you want to trigger callbacks

**Comment by Skeyelab** [comment]
awesome!  Thanks.
