### ISSUE TITLE
Query's first_or_create does not take an attributes argument?

### ISSUE THREAD

**Issue by cinkonaap** [deepcerulean/passive_record#9]
RubyMine shows me that I pass argument to `first_or_create`, which does not take any arguments.

```
def first_or_create
  first || create
end
```

But I think the intention is to pass attributes to `create` if there is no found. Am I missing something?

**Comment by jweissman** [comment]
So this is "fixed" in the PR above, but I wanted to mention some of the relational weirdness inherent in permitting this (passing args to a queries' `first_or_create`).

`#first_or_create` will "seem" like it's doing an *update* in certain cases (in particular if an `id` field is used in one of the queries.) [This spec kind of clarifies what's going on](https://github.com/deepcerulean/passive_record/pull/10/files#diff-cce442766e5779e0f3b25eeea066eaacR152), a little bit. So passing args to `first_or_create` definitely comes with the warning that if you're doing things with ids, it may not always be doing what you *might* be expecting.

**Comment by jweissman** [comment]
(And you'll have to pin to master to use this immediately -- I'll plan to get a gem release out this weekend)
